FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o freedom-core ./cmd/server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/freedom-core .
EXPOSE 80
CMD ["./freedom-core"]
